services:
  backend:
    user: "${UID}:${GID}"

    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - backend/.env

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - PORT=5173
    volumes:
      - ./web:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend
